# _config.yml

# Site Configuration
title: My CV
description: Personal CV
baseurl: "" # Leave empty for GitHub Pages

# Build Configuration
markdown: kramdown
theme: jekyll-theme-cayman # Change the theme to "jekyll-theme-cayman"

# GitHub Pages Configuration
github:
  is_project_page: false

# Customize Cayman Theme
cayman:
  show_downloads: false # Hide download links for repository files
  analytics: "" # Add your Google Analytics tracking code here if needed

# Additional Configuration (you can add more as needed)
