# _config.yml

# Site Configuration
title: My CV
description: Personal CV
baseurl: "" # Leave empty for GitHub Pages
url: "https://username.github.io" # Your GitHub Pages URL

# Build Configuration
markdown: kramdown
theme: minima # You can choose a different Jekyll theme if you prefer

# GitHub Pages Configuration
github:
  is_project_page: false

# Navigation Links
nav_links:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Experience
    url: /experience
  - text: Education
    url: /education
  - text: Skills
    url: /skills

# Social Links
social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/yourname/
  - name: GitHub
    url: https://github.com/yourusername

# Customize Minima Theme
minima:
  author: Your Name
  email: your.email@example.com
  avatar: /assets/profile.jpg
  social_links: # These are additional social links specific to the Minima theme
    - name: Twitter
      url: https://twitter.com/yourusername

# Additional Configuration (you can add more as needed)
